apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: mlflow
  labels:
    app: mlflow-server
    component: model-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: mlflow-server
          image: python:3.9-slim
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: MLFLOW_BACKEND_STORE_URI
              value: "sqlite:///mlflow/mlflow.db"
            - name: MLFLOW_DEFAULT_ARTIFACT_ROOT
              value: "/mlflow/artifacts"
            - name: MLFLOW_HOST
              value: "0.0.0.0"
            - name: MLFLOW_PORT
              value: "5000"
          command:
            - /bin/bash
            - -c
            - |
              pip install mlflow==2.8.1 psutil
              mlflow server \
                --backend-store-uri $MLFLOW_BACKEND_STORE_URI \
                --default-artifact-root $MLFLOW_DEFAULT_ARTIFACT_ROOT \
                --host $MLFLOW_HOST \
                --port $MLFLOW_PORT \
                --serve-artifacts
          volumeMounts:
            - name: mlflow-data
              mountPath: /mlflow
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: mlflow-data
          persistentVolumeClaim:
            claimName: mlflow-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-config
  namespace: mlflow
data:
  mlflow.conf: |
    # MLflow Configuration
    backend_store_uri = sqlite:///mlflow/mlflow.db
    default_artifact_root = /mlflow/artifacts
    host = 0.0.0.0
    port = 5000
    workers = 4
